'use strict';

const MALLAR = {
  ansokan: {
    rubrik: [
      'Ansökan om tillstånd enligt gällande föreskrifter',
      'Ansökan om medel enligt beslutad ram',
      'Inkommen ansökan för prövning',
      'Ansökan om tillstånd att bedriva verksamhet',
    ],
    med: [
      'Sökanden {NAMN} lämnar härmed in ansökan enligt gällande föreskrifter.',
      'Kontaktuppgifter: telefon {TELEFON}, personnummer {PERSONNUMMER}.',
      'Namnet {NAMN} anges som huvudsökande i ärendet.',
      'Bifogat finner {NAMN} begärda handlingar för prövning.',
      'Telefonnummer för återkoppling: {TELEFON}.',
      'Personnummer enligt folkbokföring: {PERSONNUMMER}.',
      'Sökanden {NAMN} intygar att uppgifterna är riktiga.',
      'Vid frågor nås {NAMN} på {TELEFON}.',
    ],
    utan: [
      'Ansökan avser medel enligt beslutad ram.',
      'Handlingen ska ha kommit in före angiven sista dag.',
      'Myndigheten gör en samlad bedömning av ärendet.',
      'Brister i underlag kan medföra att ärendet avvisas.',
      'Beslut meddelas när utredningen är klar.',
      'Kopior sparas enligt gällande arkivregler.',
      'Handläggningen sker i turordning.',
      'Eventuell komplettering begärs skriftligen.',
      'Underlaget granskas mot gällande checklista.',
      'Handläggaren noterar att ansökan är komplett.',
      'Ärendet registreras i diariet vid inkomst.',
      'Sökanden informeras om normal handläggningstid.',
      'Kompletterande uppgifter kan begäras per brev.',
      'Myndigheten kan inhämta yttrande från annan part.',
      'Avgiften ska ha erlagts innan prövning påbörjas.',
      'Handlingar returneras endast på särskild begäran.',
      'Ansökan diarieförs enligt gällande ordning.',
      'Handläggaren begär komplettering skriftligen.',
      'Myndigheten kan begära in ytterligare underlag.',
      'Prövningen sker enligt fastställd handläggningsordning.',
    ],
    arende: [
      'Sökanden begär tillstånd att bedriva verksamheten enligt bifogad beskrivning.',
      'Verksamheten avser lokaler som uppfyller gällande planbestämmelser.',
      'Ansökan avser verksamhet som omfattas av prövningsplikt enligt föreskrift.',
      'Sökanden har redovisat erforderlig kompetens för den sökta verksamheten.',
      'Tillståndet begärs för verksamhet som kan bedrivas utan olägenhet för omgivningen.',
      'Ansökan avser medel som ska användas enligt beslutad ram och villkor.',
      'Sökanden har bifogat erforderliga handlingar för prövning av ärendet.',
      'Verksamheten planeras att starta efter meddelat beslut från myndigheten.',
      'Sökanden har fått information om handläggningstid och kompletteringsmöjligheter.',
      'Ärendet har varit föremål för inledande granskning mot gällande checklista.',
      'Sökanden har lämnat uppgifter om plats och omfattning av verksamheten.',
      'Ansökan avser förnyelse av tidigare meddelat tillstånd utan ändrade villkor.',
      'Sökanden har redovisat att erforderliga tillstånd från annan myndighet inhämtats.',
      'Verksamheten bedöms kunna uppfylla ställda krav enligt gällande föreskrifter.',
      'Sökanden begär att ärendet handläggs skyndsamt med hänvisning till tidsfrist.',
      'Ansökan avser verksamhet som tidigare prövats utan anmärkning.',
      'Sökanden har lämnat kontaktuppgifter för eventuell komplettering.',
      'Ärendet har registrerats och tilldelats handläggare enligt gällande rutin.',
      'Sökanden har informerats om avgift och betalningsvillkor.',
      'Ansökan avser tillstånd med de villkor som anges i gällande föreskrifter.',
    ],
    kollision: [
      'I närheten av platsen växer det gott om {ORD}.',
      'Sökanden anger att ordet {ORD} förekommer i omgivningen.',
    ],
  },
  tjansteanteckning: {
    rubrik: [
      'Tjänsteanteckning {DATUM}',
      'Intern anteckning {DATUM}',
      'Handläggningsanteckning {DATUM}',
      'Anteckning i ärende {DATUM}',
    ],
    med: [
      'Anteckning gäller handläggning av {NAMN}.',
      'Telefonsamtal fördes med {NAMN} denna dag.',
      'Personnummer kontrollerades: {PERSONNUMMER}.',
      'Nummer {TELEFON} användes vid kontakt.',
      '{NAMN} meddelade att handlingen kompletteras.',
      'Uppgift om {PERSONNUMMER} fördes in i ärendet.',
      'Telefon {TELEFON} bekräftades som giltigt.',
      '{NAMN} hänvisade till tidigare korrespondens.',
    ],
    utan: [
      'Ärendet ligger för beslut hos enhetschef.',
      'Komplettering har begärts per post.',
      'Handläggningen återupptas efter semestertid.',
      'Journalanteckningen signeras av handläggare.',
      'Kopia skickas till berörd part.',
      'Tidsfristen förlängdes med fjorton dagar.',
      'Intern avstämning genomfördes.',
      'Status uppdaterades i ärendesystemet.',
      'Handläggaren begärde juridiskt stöd i frågan.',
      'Ärendet prioriterades om enligt rutin.',
      'Bilagor skannades och lades till i akten.',
      'Enheten avvaktar svar från annan myndighet.',
      'Anteckningen diariefördes enligt gällande ordning.',
      'Påminnelse skickades till sökanden.',
      'Handläggningstiden förlängdes efter överenskommelse.',
      'Intern notering om att ärendet är komplett.',
      'Handläggaren begärde yttrande från annan enhet.',
      'Ärendet återförts till handläggare efter semestertid.',
      'Kompletterande handlingar mottogs och registrerades.',
      'Enheten avvaktar beslut från enhetschef.',
    ],
    anteckning: [
      'Handläggaren har genomfört telefonkontakt med sökanden.',
      'Komplettering begärdes skriftligen med fjorton dagars svarstid.',
      'Ärendet ligger för beslut hos enhetschef efter intern avstämning.',
      'Handläggaren noterar att underlaget bedöms tillräckligt för prövning.',
      'Intern avstämning genomfördes med juridiskt stöd.',
      'Status uppdaterades i ärendesystemet efter mottagen komplettering.',
      'Handläggaren begärde yttrande från annan myndighet.',
      'Tidsfristen förlängdes efter överenskommelse med sökanden.',
      'Anteckningen diariefördes enligt gällande ordning.',
      'Handläggaren avvaktar svar på begärd komplettering.',
      'Ärendet prioriterades om enligt fastställd rutin.',
      'Bilagor skannades och lades till i akten.',
      'Handläggaren noterar att ärendet är komplett för beslut.',
      'Påminnelse skickades till sökanden per post.',
      'Enheten avvaktar svar från annan instans.',
      'Handläggningen återupptas efter semestertid.',
      'Intern notering om att komplettering mottagits.',
      'Handläggaren har redogjort muntligt för ärendets innehåll.',
      'Kopia av anteckningen skickades till berörd part.',
      'Journalanteckningen signeras av handläggare.',
    ],
    kollision: [
      'I omgivningen förekommer {ORD} naturligt.',
      'Texten nämner att {ORD} är relevant för platsen.',
    ],
  },
  beslut: {
    rubrik: [
      'Beslut i ärende om tillstånd enligt ansökan',
      'Beslut efter prövning av inkommen ansökan',
      'Myndighetens beslut i tillståndsärende',
      'Beslut om bifall till ansökan',
    ],
    formalia: [
      '{NAMN} är sökande i ärendet.',
      'Namn enligt ansökan: {NAMN}.',
      'Sökanden i ärendet är {NAMN}.',
      '{NAMN} anges som sökande i ärendet.',
      'Kontaktuppgifter: telefon {TELEFON}.',
      'Telefon för kontakt: {TELEFON}.',
      'Personnummer i ärendet: {PERSONNUMMER}.',
      'Telefonnummer: {TELEFON}.',
    ],
    bakgrund: [
      'Sökanden har ansökt om tillstånd enligt gällande föreskrifter.',
      'Ansökan inkom i rätt tid och registrerades i myndighetens diarium.',
      'Handlingen har granskats mot gällande checklista för tillståndsprövning.',
      'Sökanden har fått tillfälle att yttra sig över kompletterande uppgifter.',
      'Myndigheten har inhämtat erforderliga uppgifter från berörda instanser.',
      'Ärendet har varit föremål för intern handläggning hos enheten.',
      'Tillståndet avser verksamhet som omfattas av prövningsplikt.',
      'Sökanden har tidigare haft liknande tillstånd utan anmärkning.',
      'Platsen för den sökta verksamheten har bedömts mot gällande planbestämmelser.',
      'Underlaget har bedömts tillräckligt för att fatta beslut i ärendet.',
      'Handläggaren har redogjort muntligt för ärendets innehåll internt.',
      'Komplettering har inkommit och tagits in i den samlade bedömningen.',
      'Sökanden har lämnat uppgifter om verksamhetens omfattning och plats.',
      'Myndigheten har informerat sökanden om handläggningstid och rutiner.',
      'Ärendet har varit föremål för inledande granskning mot gällande checklista.',
      'Sökanden har bifogat erforderliga handlingar för prövning.',
      'Handläggaren har begärt komplettering skriftligen vid behov.',
      'Myndigheten har inhämtat yttrande från berörd instans.',
      'Ansökan diariefördes enligt gällande ordning vid inkomst.',
      'Sökanden har fått tillfälle att yttra sig innan beslut meddelades.',
    ],
    skal: [
      'Myndigheten finner att sökanden uppfyller ställda krav enligt föreskrifterna.',
      'Det finns inte skäl att avslå ansökan med hänvisning till brister i underlaget.',
      'Tillståndet kan medges med de villkor som anges i gällande föreskrifter.',
      'Prövningen har skett med beaktande av allmänna hänsyn och enskilda intressen.',
      'Myndigheten bedömer att verksamheten kan bedrivas utan olägenhet för omgivningen.',
      'Sökanden har visat att erforderlig kompetens finns för den sökta verksamheten.',
      'Det finns inte anledning att anta att villkoren inte kommer att följas.',
      'Tillståndet är förenligt med myndighetens övergripande tillsynsuppdrag.',
      'Handläggningen har skett enligt gällande rutiner för tillståndsprövning.',
      'Myndigheten har beaktat tidigare erfarenheter från liknande ärenden.',
      'Det finns inte skäl att förelägga särskilda villkor utöver standardvillkoren.',
      'Prövningen har inte gett anledning till ytterligare utredning.',
      'Sökanden har uppfyllt de formella krav som ställs enligt föreskrifterna.',
      'Myndigheten bedömer att verksamheten kan bedrivas enligt ansökan.',
      'Det finns inte skäl att anta att tillståndet kommer att missbrukas.',
      'Prövningen har skett med beaktande av gällande planbestämmelser.',
      'Sökanden har visat att erforderliga tillstånd från annan myndighet inhämtats.',
      'Myndigheten finner att ansökan är förenlig med gällande lagstiftning.',
      'Det finns inte skäl att avslå ansökan med hänvisning till platsens läge.',
      'Handläggningen har skett enligt fastställd ordning och utan dröjsmål.',
    ],
    slut: [
      'Sökandens tillstånd ges enligt ansökan.',
      'Myndigheten beviljar sökanden tillstånd enligt ansökan.',
      'Sökanden medges tillstånd att bedriva sökt verksamhet.',
      'Beslutet gäller omedelbart och ska föras i laga ordning.',
      'Tillståndet meddelas genom detta beslut.',
      'Verkställighet sker enligt angivna villkor i tillståndsbrevet.',
      'Beslutet ska delges sökanden utan dröjsmål.',
      'Överklagande kan ske enligt gällande bestämmelser.',
      'Tillståndet gäller tills vidare enligt angivna villkor.',
      'Myndigheten meddelar bifall till ansökan genom detta beslut.',
      'Sökanden medges tillstånd med de villkor som anges i föreskrifterna.',
      'Beslutet ska expedieras till sökanden utan dröjsmål.',
    ],
    kollision: [
      'Området präglas av {ORD} enligt beskrivning.',
      'I handlingen anges att {ORD} förekommer i texten.',
    ],
  },
};

const DOKUMENTTYPER = ['ansokan', 'tjansteanteckning', 'beslut'];

function valjMallar(slump) {
  const ut = {};
  for (const typ of DOKUMENTTYPER) {
    ut[typ] = MALLAR[typ];
  }
  return ut;
}

module.exports = { MALLAR, DOKUMENTTYPER, valjMallar };
